Stage
MoonSold/Vote pull request #2
Opened 2022-07-21 14:48 UTC by MoonSold

Валидация внутри сервера есть, что делать дальше не понятно

2022-07-22 18:21 UTC, anna-plsn commented
Никогда не комить файлы:
1. С точкой (Например, .idea)
2. Библиотеки (vender, extjs)

2022-07-22 18:48 UTC, anna-plsn requested changes

2022-07-22 18:48 UTC, anna-plsn commented on api/Entity/AdminEntity.php
> +    private $adminname;
NIT: Если таблица называется admin, то называть поле adminname нет смысла. Лучше просто name

2022-07-22 18:48 UTC, anna-plsn commented on api/Entity/QuestionGroupEntity.php
> + * @ORM\Table(name="questionsgroup")
NIT: questionsgroup. Слова лучше визуально разделять

2022-07-22 18:48 UTC, anna-plsn commented on api/service/AdminUserClass.php
> +class AdminUserClass
AdminUserController

2022-07-22 18:48 UTC, anna-plsn commented on api/service/AuthUserClass.php
> +    public static function authUser($login,$password):array
psr

2022-07-22 18:48 UTC, anna-plsn commented on api/service/AuthUserClass.php
> +            if ($user->getPasswordHash() == md5($password)) {
Через строгое сравнение

2022-07-22 18:48 UTC, anna-plsn commented on api/service/AuthUserClass.php
> +        try {
try catch не нужен, если это select
 Просто проверку результата БД на null и тогда return ["auth"=> false,"token" => "not auth", "username" => "not auth"];

2022-07-22 18:48 UTC, anna-plsn commented on api/service/RegisterUserClass.php
> +            if ($validation === true) {
if ($validation) {

2022-07-22 18:48 UTC, anna-plsn commented on api/service/ValidatorClass.php
> +                return true;
```
return preg_match("/^[a-zA-Z0-9-_]{5,20}$/i",$login)
                && preg_match("/^[a-zA-Z0-9-_#$^&*@!?]{5,20}$/i",$password)
                    && preg_match("/^[а-яёА-ЯЁ]+$/u",$username);
```

2022-07-22 18:48 UTC, anna-plsn commented on index.php
> +register_shutdown_function(function () {
Это не комитят, это только для отладки

2022-07-22 19:55 UTC, MoonSold commented on api/service/AdminUserClass.php
> +class AdminUserClass
Это не контроллер, это сервис. Будет соответствующая функция в котроллере работающая с этим классом

2022-07-22 19:56 UTC, MoonSold commented on api/service/ValidatorClass.php
> +                return true;
По факту

2022-07-22 19:57 UTC, MoonSold commented on index.php
> +register_shutdown_function(function () {
я понял, забыл убрать

2022-07-26 09:35 UTC, MoonSold commented
Ext js странный

2022-08-04 08:49 UTC, anna-plsn commented on api/api.php
> +else{
elseif ($_REQUEST["actor"] === "admin")

2022-08-04 08:49 UTC, anna-plsn commented on api/controller/AdminController.php
> +    public function controllerAdminAuthFunction(array $request): array
adminAuth
И так видно, что это функция в контроллере

2022-08-04 08:49 UTC, anna-plsn commented on api/service/AdminService.php
> +        register_shutdown_function(function () {
Средства для дебага не коммитят

2022-08-04 09:57 UTC, merged